version: "3.8"

services:
  backend:
    build:
      context: ../backend
    privileged: true
    ports:
      - "5000:5000"
    restart: always
    devices:
      - /dev/snd:/dev/snd  # Give container access to ALSA devices
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - XDG_RUNTIME_DIR=/tmp/pulse
    volumes:
      - /run/user/1000/pulse/native:/tmp/pulse/native  # Mount host PulseAudio socket (change 1000 to your UID)
      - /etc/machine-id:/etc/machine-id:ro  # Needed by PulseAudio auth sometimes



  frontend:
    build:
      context: ../frontend
    privileged: true
    ports:
      - "3000:80"
    restart: always